### ISSUE TITLE
error in tensorflow 1.0

### ISSUE THREAD

**Issue by xslittlegrass** [yoavz/music_rnn#6]
I encountered an error when using tensorflow 1.0:

```
Traceback (most recent call last):
  File "rnn.py", line 142, in <module>
    data["train"]["data"], training=True, testing=False)
  File "/Users/xslittlegrass/Downloads/music_rnn/util.py", line 190, in run_epoch
    state = model.get_cell_zero_state(session, batch_size) 
  File "/Users/xslittlegrass/Downloads/music_rnn/model.py", line 101, in get_cell_zero_state
    return self.cell.zero_state(batch_size, tf.float32).eval(session=session)
AttributeError: 'tuple' object has no attribute 'eval'
```

Does anyone have any suggestions? Thanks.

**Comment by Eumi** [comment]
check out https://github.com/llSourcell/AI_Composer
